import { contactType } from "../../types";

export const contacts: contactType[] = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-202-555-0143",
    category: "Employee",
    gender: "Male",
    location: "New York, USA",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+44-20-7946-0958",
    category: "Customer",
    location: "London, UK",
    gender: "Female",
  },
  {
    name: "Robert Brown",
    email: "robert.brown@example.com",
    phone: "+61-2-9374-8922",
    category: "Partner",
    location: "Sydney, Australia",
    gender: "Male",
  },
  {
    name: "Emily Johnson",
    email: "emily.johnson@example.com",
    phone: "+1-303-555-0172",
    category: "Employee",
    location: "Denver, USA",
    gender: "Female",
  },
  {
    name: "Michael Davis",
    email: "michael.davis@example.com",
    phone: "+49-30-555-0184",
    category: "Customer",
    location: "Berlin, Germany",
    gender: "Male",
  },
  {
    name: "Sophia Lee",
    email: "sophia.lee@example.com",
    phone: "+82-2-123-4567",
    category: "Partner",
    location: "Seoul, South Korea",
    gender: "Female",
  },
  {
    name: "David Martinez",
    email: "david.martinez@example.com",
    phone: "+34-91-123-4567",
    category: "Employee",
    location: "Madrid, Spain",
    gender: "Male",
  },
  {
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    phone: "+1-415-555-0199",
    category: "Customer",
    location: "San Francisco, USA",
    gender: "Female",
  },
  {
    name: "Lucas Kim",
    email: "lucas.kim@example.com",
    phone: "+82-2-987-6543",
    category: "Partner",
    location: "Busan, South Korea",
    gender: "Male",
  },
  {
    name: "Olivia Nguyen",
    email: "olivia.nguyen@example.com",
    phone: "+61-3-9123-4567",
    category: "Customer",
    location: "Melbourne, Australia",
    gender: "Female",
  },
  {
    name: "Liam Walker",
    email: "liam.walker@example.com",
    phone: "+1-202-555-0123",
    category: "Employee",
    location: "Washington, USA",
    gender: "Male",
  },
  {
    name: "Ava Thompson",
    email: "ava.thompson@example.com",
    phone: "+44-20-7946-0897",
    category: "Customer",
    location: "Manchester, UK",
    gender: "Female",
  },
  {
    name: "Noah White",
    email: "noah.white@example.com",
    phone: "+61-2-9374-8754",
    category: "Partner",
    location: "Brisbane, Australia",
    gender: "Male",
  },
  {
    name: "Isabella Harris",
    email: "isabella.harris@example.com",
    phone: "+1-303-555-0147",
    category: "Employee",
    location: "Chicago, USA",
    gender: "Female",
  },
  {
    name: "Mason Martin",
    email: "mason.martin@example.com",
    phone: "+49-30-555-0123",
    category: "Customer",
    location: "Hamburg, Germany",
    gender: "Male",
  },
  {
    name: "Mia Lewis",
    email: "mia.lewis@example.com",
    phone: "+82-2-123-8945",
    category: "Partner",
    location: "Incheon, South Korea",
    gender: "Female",
  },
  {
    name: "James Clark",
    email: "james.clark@example.com",
    phone: "+34-91-123-5432",
    category: "Employee",
    location: "Barcelona, Spain",
    gender: "Male",
  },
  {
    name: "Ella Robinson",
    email: "ella.robinson@example.com",
    phone: "+1-415-555-0143",
    category: "Customer",
    location: "Los Angeles, USA",
    gender: "Female",
  },
  {
    name: "William Rodriguez",
    email: "william.rodriguez@example.com",
    phone: "+82-2-987-6712",
    category: "Partner",
    location: "Seoul, South Korea",
    gender: "Male",
  },
  {
    name: "Sophia Moore",
    email: "sophia.moore@example.com",
    phone: "+61-3-9123-0987",
    category: "Customer",
    location: "Perth, Australia",
    gender: "Female",
  },
  {
    name: "Benjamin Jackson",
    email: "benjamin.jackson@example.com",
    phone: "+1-202-555-0987",
    category: "Employee",
    location: "Houston, USA",
    gender: "Male",
  },
  {
    name: "Charlotte Lopez",
    email: "charlotte.lopez@example.com",
    phone: "+44-20-7946-0765",
    category: "Customer",
    location: "Birmingham, UK",
    gender: "Female",
  },
  {
    name: "Lucas Lee",
    email: "lucas.lee@example.com",
    phone: "+61-2-9374-5678",
    category: "Partner",
    location: "Adelaide, Australia",
    gender: "Male",
  },
  {
    name: "Amelia King",
    email: "amelia.king@example.com",
    phone: "+1-303-555-0193",
    category: "Employee",
    location: "Phoenix, USA",
    gender: "Female",
  },
  {
    name: "Henry Scott",
    email: "henry.scott@example.com",
    phone: "+49-30-555-0983",
    category: "Customer",
    location: "Munich, Germany",
    gender: "Male",
  },
  {
    name: "Harper Young",
    email: "harper.young@example.com",
    phone: "+82-2-123-4123",
    category: "Partner",
    location: "Busan, South Korea",
    gender: "Female",
  },
  {
    name: "Alexander Allen",
    email: "alexander.allen@example.com",
    phone: "+34-91-123-0987",
    category: "Employee",
    location: "Valencia, Spain",
    gender: "Male",
  },
  {
    name: "Evelyn Hernandez",
    email: "evelyn.hernandez@example.com",
    phone: "+1-415-555-0321",
    category: "Customer",
    location: "Seattle, USA",
    gender: "Female",
  },
  {
    name: "Michael Wright",
    email: "michael.wright@example.com",
    phone: "+82-2-987-5432",
    category: "Partner",
    location: "Daegu, South Korea",
    gender: "Male",
  },
  {
    name: "Abigail Green",
    email: "abigail.green@example.com",
    phone: "+61-3-9123-4560",
    category: "Customer",
    location: "Hobart, Australia",
    gender: "Female",
  },
  {
    name: "Daniel Baker",
    email: "daniel.baker@example.com",
    phone: "+1-202-555-0786",
    category: "Employee",
    location: "San Diego, USA",
    gender: "Male",
  },
  {
    name: "Ella Perez",
    email: "ella.perez@example.com",
    phone: "+44-20-7946-0567",
    category: "Customer",
    location: "Liverpool, UK",
    gender: "Female",
  },
  {
    name: "Matthew Hill",
    email: "matthew.hill@example.com",
    phone: "+61-2-9374-5431",
    category: "Partner",
    location: "Canberra, Australia",
    gender: "Male",
  },
  {
    name: "Avery Adams",
    email: "avery.adams@example.com",
    phone: "+1-303-555-0543",
    category: "Employee",
    location: "Dallas, USA",
    gender: "Female",
  },
  {
    name: "Jack Nelson",
    email: "jack.nelson@example.com",
    phone: "+49-30-555-0213",
    category: "Customer",
    location: "Frankfurt, Germany",
    gender: "Male",
  },
  {
    name: "Chloe Carter",
    email: "chloe.carter@example.com",
    phone: "+82-2-123-5678",
    category: "Partner",
    location: "Gwangju, South Korea",
    gender: "Female",
  },
  {
    name: "Jacob Mitchell",
    email: "jacob.mitchell@example.com",
    phone: "+34-91-123-6578",
    category: "Employee",
    location: "Seville, Spain",
    gender: "Male",
  },
  {
    name: "Sofia Roberts",
    email: "sofia.roberts@example.com",
    phone: "+1-415-555-0789",
    category: "Customer",
    location: "Portland, USA",
    gender: "Female",
  },
  {
    name: "Jayden Lewis",
    email: "jayden.lewis@example.com",
    phone: "+82-2-987-1234",
    category: "Partner",
    location: "Ulsan, South Korea",
    gender: "Male",
  },
  {
    name: "Grace Walker",
    email: "grace.walker@example.com",
    phone: "+61-3-9123-7890",
    category: "Customer",
    location: "Gold Coast, Australia",
    gender: "Female",
  },
];
